// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: foochain/foo/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "foochain/x/lightclient/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Message to request verification of tx
type MsgVerifyTxRequest struct {
	Sender      string        `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	TxHash      string        `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHeight int64         `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Proof       *types.Proof  `protobuf:"bytes,4,opt,name=proof,proto3" json:"proof,omitempty"`
	TxData      *types.TxData `protobuf:"bytes,5,opt,name=tx_data,json=txData,proto3" json:"tx_data,omitempty"`
}

func (m *MsgVerifyTxRequest) Reset()         { *m = MsgVerifyTxRequest{} }
func (m *MsgVerifyTxRequest) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyTxRequest) ProtoMessage()    {}
func (*MsgVerifyTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61816751bbbe05d9, []int{0}
}
func (m *MsgVerifyTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyTxRequest.Merge(m, src)
}
func (m *MsgVerifyTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyTxRequest proto.InternalMessageInfo

func (m *MsgVerifyTxRequest) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgVerifyTxRequest) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *MsgVerifyTxRequest) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *MsgVerifyTxRequest) GetProof() *types.Proof {
	if m != nil {
		return m.Proof
	}
	return nil
}

func (m *MsgVerifyTxRequest) GetTxData() *types.TxData {
	if m != nil {
		return m.TxData
	}
	return nil
}

// Response for the VerifyTx rpc method
type MsgVerifyTxResponse struct {
	Verified bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
}

func (m *MsgVerifyTxResponse) Reset()         { *m = MsgVerifyTxResponse{} }
func (m *MsgVerifyTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVerifyTxResponse) ProtoMessage()    {}
func (*MsgVerifyTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61816751bbbe05d9, []int{1}
}
func (m *MsgVerifyTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVerifyTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVerifyTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVerifyTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVerifyTxResponse.Merge(m, src)
}
func (m *MsgVerifyTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVerifyTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVerifyTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVerifyTxResponse proto.InternalMessageInfo

func (m *MsgVerifyTxResponse) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func init() {
	proto.RegisterType((*MsgVerifyTxRequest)(nil), "foochain.foo.MsgVerifyTxRequest")
	proto.RegisterType((*MsgVerifyTxResponse)(nil), "foochain.foo.MsgVerifyTxResponse")
}

func init() { proto.RegisterFile("foochain/foo/tx.proto", fileDescriptor_61816751bbbe05d9) }

var fileDescriptor_61816751bbbe05d9 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x3d, 0x4f, 0xc2, 0x50,
	0x14, 0xe5, 0x89, 0x20, 0x3e, 0x98, 0x9e, 0x1f, 0x34, 0xd5, 0x34, 0x85, 0xc1, 0x10, 0x87, 0x36,
	0x60, 0x5c, 0x1c, 0x8d, 0x03, 0x0b, 0xd1, 0x34, 0x84, 0xc1, 0x85, 0x3c, 0xca, 0xeb, 0x47, 0x84,
	0xde, 0xda, 0xfb, 0x24, 0x65, 0xf5, 0x17, 0xf8, 0x53, 0xfc, 0x19, 0x8e, 0x8c, 0x6e, 0x1a, 0x18,
	0xfc, 0x1b, 0xa6, 0x2d, 0x34, 0x18, 0x8d, 0xd3, 0x7b, 0xf7, 0xdc, 0x73, 0x72, 0xef, 0xb9, 0x87,
	0x1e, 0x39, 0x00, 0xb6, 0xc7, 0xfd, 0xc0, 0x74, 0x00, 0x4c, 0x19, 0x1b, 0x61, 0x04, 0x12, 0x58,
	0x6d, 0x03, 0x1b, 0x0e, 0x80, 0x7a, 0x96, 0x93, 0x26, 0xbe, 0xeb, 0x49, 0x7b, 0xe2, 0x8b, 0x40,
	0x6e, 0xff, 0x33, 0x95, 0x5a, 0xb7, 0x01, 0xa7, 0x80, 0xe6, 0x14, 0x5d, 0x73, 0xd6, 0x4e, 0x9e,
	0xac, 0xd1, 0xfc, 0x20, 0x94, 0xf5, 0xd0, 0x1d, 0x88, 0xc8, 0x77, 0xe6, 0xfd, 0xd8, 0x12, 0x8f,
	0x4f, 0x02, 0x25, 0x3b, 0xa6, 0x65, 0x14, 0xc1, 0x58, 0x44, 0x0a, 0xd1, 0x49, 0x6b, 0xdf, 0x5a,
	0x57, 0xac, 0x4e, 0xf7, 0x64, 0x3c, 0xf4, 0x38, 0x7a, 0xca, 0x4e, 0xd6, 0x90, 0x71, 0x97, 0xa3,
	0xc7, 0x1a, 0xb4, 0x36, 0x9a, 0x80, 0xfd, 0x30, 0xf4, 0x44, 0x32, 0x5c, 0x29, 0xea, 0xa4, 0x55,
	0xb4, 0xaa, 0x29, 0xd6, 0x4d, 0x21, 0xd6, 0xa6, 0xa5, 0x30, 0x02, 0x70, 0x94, 0x5d, 0x9d, 0xb4,
	0xaa, 0x9d, 0x13, 0x23, 0x77, 0xb2, 0xbd, 0xef, 0x5d, 0x42, 0xb1, 0x32, 0x26, 0xbb, 0x4c, 0xc7,
	0x8d, 0xb9, 0xe4, 0x4a, 0x29, 0x15, 0x9d, 0xfe, 0x2d, 0xea, 0xc7, 0x37, 0x5c, 0xf2, 0x64, 0x99,
	0xe4, 0xbd, 0xaa, 0x3e, 0x7f, 0xbd, 0x9e, 0xaf, 0x57, 0x6e, 0xb6, 0xe9, 0xc1, 0x0f, 0x83, 0x18,
	0x42, 0x80, 0x82, 0xa9, 0xb4, 0x32, 0x4b, 0x30, 0x5f, 0x8c, 0x53, 0x8f, 0x15, 0x2b, 0xaf, 0x3b,
	0x03, 0x5a, 0xec, 0xa1, 0xcb, 0x6e, 0x69, 0x65, 0x23, 0x63, 0xba, 0xb1, 0x7d, 0x77, 0xe3, 0xf7,
	0xc9, 0xd4, 0xc6, 0x3f, 0x8c, 0x6c, 0xe6, 0xb5, 0xf1, 0xb6, 0xd4, 0xc8, 0x62, 0xa9, 0x91, 0xcf,
	0xa5, 0x46, 0x5e, 0x56, 0x5a, 0x61, 0xb1, 0xd2, 0x0a, 0xef, 0x2b, 0xad, 0x70, 0x7f, 0x98, 0xe7,
	0x18, 0x67, 0x71, 0xcf, 0x43, 0x81, 0xa3, 0x72, 0x9a, 0xd1, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xfb, 0x9a, 0xde, 0x72, 0x0b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	VerifyTx(ctx context.Context, in *MsgVerifyTxRequest, opts ...grpc.CallOption) (*MsgVerifyTxResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) VerifyTx(ctx context.Context, in *MsgVerifyTxRequest, opts ...grpc.CallOption) (*MsgVerifyTxResponse, error) {
	out := new(MsgVerifyTxResponse)
	err := c.cc.Invoke(ctx, "/foochain.foo.Msg/VerifyTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	VerifyTx(context.Context, *MsgVerifyTxRequest) (*MsgVerifyTxResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) VerifyTx(ctx context.Context, req *MsgVerifyTxRequest) (*MsgVerifyTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTx not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_VerifyTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVerifyTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VerifyTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foochain.foo.Msg/VerifyTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VerifyTx(ctx, req.(*MsgVerifyTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foochain.foo.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyTx",
			Handler:    _Msg_VerifyTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foochain/foo/tx.proto",
}

func (m *MsgVerifyTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyTxRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyTxRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TxData != nil {
		{
			size, err := m.TxData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Proof != nil {
		{
			size, err := m.Proof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVerifyTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVerifyTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVerifyTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgVerifyTxRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	if m.Proof != nil {
		l = m.Proof.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TxData != nil {
		l = m.TxData.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVerifyTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Verified {
		n += 2
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgVerifyTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proof == nil {
				m.Proof = &types.Proof{}
			}
			if err := m.Proof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxData == nil {
				m.TxData = &types.TxData{}
			}
			if err := m.TxData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVerifyTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVerifyTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVerifyTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
